pipeline {
    agent any
    options {
        timeout(time: 1, unit: 'HOURS') 
    }
    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        stage('Maven info') {
            steps {
                sh 'which mvn'
                sh 'which java'
                sh 'mvn --version'
            }
        }
        stage('Build') {
            steps {
                dir 'asciidoctor-maven-example' {
                    sh 'mvn -B clean package'
                }
            }
        }
    }
}