pipeline {
    agent any
    options {
        timeout(time: 1, unit: 'HOURS') 
    }
    stages {
        stage('Repo checkout') {
            steps {
                checkout scm
            }
        }
        stage('Maven info') {
            steps {
                sh '''
                    which mvn
                    which java
                    mvn --version
                '''
            }
        }
        stage('Build') {
            steps {
                dir ('asciidoctor-maven-example') {
                    sh 'mvn -B clean package'
                }
            }
        }
    }
    post {
        always {
            archiveArtifacts artifacts: '**/generated-docs/**/*.html,**/generated-docs/**/*.svg,**/generated-docs/**/*.png', fingerprint: true
        }
    }
}