scrape_configs:
  # Configuration to poll from Thorntail
  - job_name: 'thorntail'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:8280']
# Configuration to poll from WildFly
  - job_name: 'wildfly'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:10090']
  # Configuration to poll from OpenLiberty
  - job_name: 'liberty'
    scrape_interval: 15s
    scheme: https
    basic_auth:
      username: 'theUser'
      password: 'thePassword'
    tls_config:
      insecure_skip_verify: true
    # translates to https://localhost:9443/metrics
    static_configs:
      - targets: ['localhost:9443']
  # Configuration to poll from Payara
  - job_name: 'payara'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:7080']
# Configuration to poll from Helidon
  - job_name: 'helidon'
    scrape_interval: 15s
    static_configs:
      - targets: ['localhost:8080']
